# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-29 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation', '0003_project_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='favourite',
            new_name='favorite',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='_lowername',
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.IntegerField(default=0),
        ),
    ]
